### PR TITLE
Update for 2.4.2 and 2.5.0

### PR DESCRIPTION
**Pull request by GlenCFL**
This also includes the grammar from the TypeScript branch, though there is one suggestion that had to be commented out for now.

### CODE REVIEW

**Comment by callum-ramage** [comment]
Didn't even get a chance to start working on this. I'll check the changes tonight, thanks!

**Comment by GlenCFL** [comment]
There will be a new corrupted rule (probably taking a boolean) according to [this post](https://www.reddit.com/r/pathofexile/comments/5fs35o/ggg_can_we_get_more_lootfilter_sounds/dammblp/), but there's no information on it available yet. I assume it might sneak into the 2.5 release.

**Comment by callum-ramage** [comment]
Yeah, I saw that as well. I'd expect a modified Identified tag to work for it but we will have to wait and see.

**Comment by GlenCFL** [comment]
[This post](https://www.pathofexile.com/forum/view-thread/1774440/) has been updated, with the following:

>Items filters can now see whether an item is corrupted with "corrupted true". 

I think that's a typo because the casing doesn't match any of the other keywords.

**Comment by GlenCFL** [comment]
I got a response from Bex and it seems that the corrupted will be case insensitive.

**Comment by callum-ramage** [comment]
Managed to get the patch out but stuffed up the version because apm and github tokens constantly stuff me up. Anyway, thanks for the help. It's greatly appreciated.

**Pull request merged**
