### PR TITLE
Typescript Merge

### PR DESCRIPTION
**Pull request by GlenCFL**
This includes some pretty significant changes to how the package functions, including the change to the language it's written in.

This does not include a linter, but is instead intended to have feature parity with the older code. The changelog has most of the changes over that code, though anything too technical was left out. I've tested it pretty thoroughly, but only locally.

### CODE REVIEW

**Comment by GlenCFL** [comment]
Closed the Linter issue due to a lot of it being irrelevant at this point. I still intend to write it, probably for 2.6 even. The previous implementation was poor due to my lack of knowledge of the Atom API, with most of it being scrapped.

**Comment by callum-ramage** [comment]
Do I need to install node.js or npm to work on this? Or is there another way?
I'm having issues with the require keyword.

I'm also getting "Cannot find module 'atom-package-deps'" but I think that might be related to the require issue.

The code looks great, might take me a little bit to get my head around it though.

**Comment by GlenCFL** [comment]
If you're trying to set it up for local development, then yes. You could use the npm bundled with Atom if you were to find it on disk, but it's probably easier to just install Node somewhere and use the NPM from it. Once it's installed and in the PATH, you'd need to run "npm install" from a command prompt or Bourne shell with the current working directly being the location of the package.

The first issue is a missing development dependency, in particular the type definitions for Node. TypeScript will look into 'node-modules' when trying to resolve modules, which wont exist until you run NPM. The second is a missing normal dependency. I don't know if we have to worry about this later when/if the package is updated on NPM.

**Comment by callum-ramage** [comment]
Seems to work correctly except that comments aren't recognised after filter expressions.
`Sockets > 2 #asedsa`
Not that this worked before anyway :P

Anything you want me to work on?

**Comment by GlenCFL** [comment]
This is where the distinction between actions and filter expressions matters. You can have trailing comments for only the actions, which a lot of filters use to apply color schemes.

Some things that I've been thinking about implementing at some point:
- Filter previewing, an example of which can be found [here](https://bschug.github.io/poedit/poedit.html), that works similarly to markdown preview. This will probably rely on data/code from the Linter, as that will give information about each line of a filter. Work could still be started on it, with some mimic data in the interim.
- Commands
  - Simple ones that just toggle configuration values or ones that display a prompt to append a value to one of the whitelists.
  - Application of a color scheme, with a file picker. You'd have to look into how [Filtration](https://github.com/ben-wallis/Filtration) does it, since that markup is what people are accustomed to.
- Additional extras for "./data/suggestions.json".
- A colorized decoration for action rules with a color value, such as SetBackgroundColor, which make that color appear within the editor in some way. Not sure what the decoration would be, but maybe something in the gutter of the editor.

One thing to note is that the type definitions for Atom aren't complete, so if something from the API listing is missing, then that's why.

**Comment by GlenCFL** [comment]
If you don't like the keyword suggestion conversion from snippets to text, then I can revert and cherrypick from the other changes.

The linter messages combined with completion results are a better guide for users, in my opinion.

**Comment by GlenCFL** [comment]
Gutter decorations are the last thing that I wanted to implement for this release. Just waiting on the loot filter data to shift things around in the data files.

**Comment by GlenCFL** [comment]
I still don't know if you want to accept this TypeScript changeover. It's up to you to publish this. I suggest we bump to 1.0.0, but otherwise just edit CHANGELOG.md.

**Comment by callum-ramage** [comment]
I'm pretty happy to accept it. It seems to work correctly for me. Just need to add a comment on how to install Linter in the README because it wasn't completely obvious.

**Comment by GlenCFL** [comment]
Linter isn't included with Atom?

**Comment by GlenCFL** [comment]
That commit should take care of this. It's the reason atom-package-deps was added in the first place.

**Comment by callum-ramage** [comment]
It wasn't included in mine but I fist installed it a long time ago so maybe that's the reason.
Great work by the way. I'm pretty sure you've put more work into this project than I have.

**Pull request merged**
